import { Ipieces } from "@/types/pieces";

const pieces: Ipieces[] = [
  {
    id: "a",
    layout: {
      grid: ["2", "2"],
      units: [
        "bg-blue-800 rounded shadow-ltLlSr",
        "",
        "",
        "bg-blue-800 rounded shadow-ltLlSr",
      ],
    },
    coords: [106, 85],
    isPositionned: false,
  },
  {
    id: "b",
    layout: {
      grid: ["2", "2"],
      units: [
        "bg-anthracite-500 rounded-t shadow-ltLlSr",
        "",
        "bg-anthracite-500 rounded-bl shadow-llSb",
        "bg-anthracite-500 rounded-r shadow-ltSbSr",
      ],
    },
    coords: [105, 45],
    isPositionned: false,
  },
  {
    id: "c",
    layout: {
      grid: ["3", "4"],
      units: [
        "bg-blue-600 rounded-tl shadow-ltLl",
        "bg-blue-600 shadow-lt",
        "bg-blue-400 rounded-r shadow-ltSbSr",
        "bg-blue-600  shadow-ll",
        "bg-blue-600 rounded-br shadow-sbSr",
        "",
        "bg-blue-600 shadow-llSr",
        "",
        "",
        "bg-blue-600 rounded-b shadow-llSbSr",
        "",
        "",
      ],
    },
    coords: [-20, 87],
    isPositionned: false,
  },
  {
    id: "d",
    layout: {
      grid: ["1", "2"],
      units: [
        "bg-anthracite-500 rounded-t shadow-ltLlSr marker:bg-blue-400",
        "bg-anthracite-500 rounded-b shadow-llSbSr endAnimation marker:bg-blue-400",
      ],
    },
    coords: [19, -3],
    isPositionned: false,
  },
  {
    id: "e",
    layout: {
      grid: ["1", "2"],
      units: [
        "bg-anthracite-500 rounded-t shadow-ltLlSr marker:bg-champagne-600",
        "bg-anthracite-500 rounded-b shadow-llSbSr endAnimation marker:bg-champagne-600",
      ],
    },
    coords: [19, 103],
    isPositionned: false,
  },
  {
    id: "f",
    layout: {
      grid: ["3", "3"],
      units: [
        "bg-blue-700 rounded-tl shadow-ltLl",
        "bg-blue-700 shadow-lt",
        "bg-blue-700 rounded-r shadow-ltSbSr",
        "bg-blue-700 shadow-ll",
        "bg-blue-700  shadow-sr",
        "",
        "bg-blue-700 rounded-bl shadow-llSb",
        "bg-anthracite-500 rounded-br shadow-SbSr",
        "",
      ],
    },
    coords: [-27, 68],
    isPositionned: false,
  },
  {
    id: "g",
    layout: {
      grid: ["4", "5"],
      units: [
        "",
        "bg-blue-700 rounded-tl shadow-ltLl",
        "bg-blue-700 rounded-tr shadow-ltSr",
        "",
        "bg-blue-700 rounded-tl shadow-ltLl",
        "bg-blue-700",
        "bg-blue-700 shadow-sr",
        "",
        "bg-blue-700 shadow-ll",
        "bg-anthracite-500 shadow-sb",
        "bg-anthracite-500 shadow-sb",
        "bg-anthracite-500 lt rounded-r shadow-ltSbSr",
        "bg-anthracite-500 shadow-sr",
        "",
        "",
        "",
        "bg-blue-500 rounded-b shadow-llSbSr",
        "",
        "",
        "",
      ],
    },
    coords: [92, -33],
    isPositionned: false,
  },
  {
    id: "h",
    layout: {
      grid: ["2", "5"],
      units: [
        "bg-anthracite-500 rounded-t shadow-ltLlSr",
        "",
        "bg-anthracite-500 shadow-llSr",
        "",
        "bg-anthracite-500 shadow-llSr",
        "",
        "bg-anthracite-500 shadow-llSr",
        "",
        "bg-anthracite-500 rounded-bl shadow-llSb",
        "bg-anthracite-500 rounded-r shadow-ltSbSr",
      ],
    },
    coords: [-20, 37],
    isPositionned: false,
  },
  {
    id: "i",
    layout: {
      grid: ["3", "2"],
      units: [
        "",
        "",
        "bg-anthracite-500 rounded-t shadow-ltLlSr",
        "bg-anthracite-500 rounded-l shadow-ltLlSb",
        "bg-anthracite-500 shadow-ltSb",
        "bg-anthracite-500 rounded-br shadow-sbSr",
      ],
    },

    coords: [105, -5],
    isPositionned: false,
  },
  {
    id: "j",
    layout: {
      grid: ["2", "3"],
      units: [
        "bg-anthracite-500 rounded-t shadow-ltLlSr marker:bg-champagne-600",
        "",
        "bg-anthracite-500 shadow-llSr marker:bg-champagne-600",
        "",
        "bg-anthracite-500 rounded-bl shadow-llSb marker:bg-champagne-600",
        "bg-anthracite-500 rounded-r shadow-ltSbSr marker:bg-champagne-600",
      ],
    },
    coords: [107, 63],
    isPositionned: false,
  },
  {
    id: "k",
    layout: {
      grid: ["3", "5"],
      units: [
        "bg-transparent endzone-k",
        "bg-blue-400 shadow-ltLlSr",
        "",
        "bg-blue-600 shadow-ltLl",
        "bg-blue-400 shadow-sr",
        "",
        "bg-blue-600 shadow-ll",
        "bg-blue-400 shadow-sr",
        "",
        "bg-blue-600 shadow-ll",
        "bg-blue-600 shadow-sb",
        "bg-blue-400 rounded-br shadow-ltSbSr",
        "bg-blue-600 rounded-b shadow-llSbSr",
        "",
        "",
      ],
    },
    coords: [104, 10],
    isPositionned: false,
  },
  {
    id: "l",
    layout: {
      grid: ["5", "6"],
      units: [
        "bg-transparent endzone-l",
        "bg-transparent",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500 shadow-lt",
        "bg-blue-600 shadow-ltSr",
        "bg-transparent",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500 ",
        "bg-blue-500 ",
        "bg-blue-600 shadow-sr",
        "bg-transparent",
        "bg-blue-500 shadow-ll",
        "bg-blue-500 ",
        "bg-blue-500 shadow-sb",
        "bg-blue-600 shadow-sbSr rounded-br",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500",
        "bg-blue-500 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-llSb rounded-bl",
        "bg-blue-500 shadow-sb",
        "bg-blue-500 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-600 rounded-bl shadow-llSbSr",
        "bg-transparent",
        "bg-transparent",
      ],
    },
    coords: [85, 102],
    isPositionned: false,
  },
  {
    id: "m",
    layout: {
      grid: ["3", "1"],
      units: [
        "bg-magenta-500 shadow-ltLlSb rounded-l marker:bg-champagne-600",
        "bg-magenta-500 shadow-ltSb marker:bg-champagne-600",
        "bg-magenta-500 shadow-ltSbSr rounded-r marker:bg-champagne-600",
      ],
    },
    coords: [42, -5],
    isPositionned: false,
  },
  {
    id: "n",
    layout: {
      grid: ["6", "5"],
      units: [
        "bg-transparent endzone-n",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-800 rounded-tr shadow-ltLlSr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-800 shadow-llSr",
        "bg-transparent",
        "bg-blue-600 rounded-tl shadow-ltLl",
        "bg-blue-600 shadow-lt",
        "bg-blue-400 shadow-lt",
        "bg-blue-400 shadow-lt",
        "bg-blue-500 shadow-sr",
        "bg-blue-600 rounded-tl shadow-ltLlSb",
        "bg-blue-600 shadow-sb",
        "bg-blue-400",
        "bg-blue-400 shadow-sb",
        "bg-blue-500 shadow-sb",
        "bg-blue-500 shadow-sbSr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-400 shadow-llSbSr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
      ],
    },
    coords: [-23, -32],
    isPositionned: false,
  },
  {
    id: "o",
    layout: {
      grid: ["6", "6"],
      units: [
        "bg-transparent endzone-o",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500 shadow-lt",
        "bg-blue-600 shadow-ltSr rounded-tr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-600 shadow-ltSr rounded-tr",
        "bg-transparent",
        "bg-blue-500 shadow-llSb ",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500 shadow-sb",
        "bg-blue-500 shadow-sb",
        "bg-blue-600 shadow-ltSbSr rounded-tr",
        "bg-transparent",
        "bg-blue-500 shadow-ll",
        "bg-blue-500 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-llSr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-llSbSr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
      ],
    },
    coords: [-30, 0],
    isPositionned: false,
  },
  {
    id: "p",
    layout: {
      grid: ["5", "4"],
      units: [
        "bg-blue-600 rounded-tl shadow-ltLl",
        "bg-blue-400 shadow-lt",
        "bg-blue-400 rounded-tr shadow-ltSr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-600 shadow-ll",
        "bg-blue-600",
        "bg-blue-400",
        "bg-blue-500 rounded-tr shadow-ltSr",
        "bg-transparent",
        "bg-blue-600 rounded-bl shadow-llSb",
        "bg-blue-600",
        "bg-blue-400",
        "bg-blue-400 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-600 rounded-bl shadow-llSb",
        "bg-blue-600 shadow-sb",
        "bg-blue-400 shadow-sb",
        "bg-blue-400 shadow-ltSbSr",
      ],
    },
    coords: [36, -35],
    isPositionned: false,
  },
  {
    id: "q",
    layout: {
      grid: ["5", "4"],
      units: [
        "bg-transparent",
        "bg-blue-500 shadow-ltLl",
        "bg-blue-500 shadow-lt",
        "bg-blue-500 shadow-ltSr",
        "bg-transparent",
        "bg-blue-500 shadow-ltLlSb",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500 shadow-ltSbSr",
        "bg-transparent",
        "bg-blue-500 shadow-ll",
        "bg-blue-500",
        "bg-blue-500 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-llSb",
        "bg-blue-500 shadow-sb",
        "bg-blue-500 shadow-sbSr rounded-br",
        "bg-transparent",
      ],
    },
    coords: [-20, 112],
    isPositionned: false,
  },
  {
    id: "r",
    layout: {
      grid: ["6", "5"],
      units: [
        "bg-transparent endzone-r",
        "bg-transparent",
        "bg-blue-500 rounded-t shadow-ltLlSr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 rounded-l shadow-ltLlSb",
        "bg-blue-500 shadow-lt",
        "bg-blue-500 shadow-sr",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-ll",
        "bg-blue-500",
        "bg-blue-500 shadow-lt",
        "bg-blue-500 shadow-ltSr",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-ll",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500",
        "bg-blue-500 shadow-ltSbSr rounded-r",
        "bg-transparent",
        "bg-transparent",
        "bg-blue-500 shadow-llSb",
        "bg-blue-500 shadow-sb",
        "bg-blue-500 shadow-sbSr rounded-br",
        "bg-transparent",
      ],
    },
    coords: [31, 105],
    isPositionned: false,
  },
];

export default pieces;
