import { Islots } from "@/types/slots";

const slots: Islots = {
  layout: {
    grid: ["13", "18"],
    rows: [
      {
        id: 1,
        units: [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "shadow-itIl rounded-tl endzone-f",
          "shadow-it rounded-none",
          "shadow-it rounded-r",
        ],
      },
      {
        id: 2,
        units: [
          "",
          "",
          "",
          "",
          "shadow-itIl rounded endzone-a",
          "",
          "",
          "bg-transparent endzone-g",
          "shadow-itIl rounded-tl",
          "shadow-it rounded-none",
          "rounded-none patch",
          "rounded-none",
          "",
        ],
      },
      {
        id: 3,
        units: [
          "",
          "",
          "",
          "",
          "",
          "shadow-itIl rounded",
          "",
          "shadow-itIl rounded-tl",
          "rounded-none patch",
          "rounded-none",
          "rounded-none",
          "rounded-none rounded-br",
          "",
        ],
      },
      {
        id: 4,
        units: [
          "",
          "bg-transparent endzone-n",
          "",
          "",
          "",
          "",
          "shadow-itIl rounded-tl",
          "patch",
          "rounded-none",
          "rounded-none",
          "rounded-none rounded-br",
          "",
          "",
        ],
      },
      {
        id: 5,
        units: [
          "",
          "",
          "",
          "",
          "",
          "",
          "shadow-il",
          "rounded-none",
          "",
          "",
          "",
          "",
          "",
        ],
      },
      {
        id: 6,
        units: [
          "",
          "",
          "rounded-tl shadow-itIl",
          "shadow-it",
          "shadow-it",
          "shadow-it",
          "rounded-none patch",
          "rounded-none endzone-o",
          "shadow-it",
          "shadow-it",
          "shadow-it rounded-tr",
          "",
          "",
        ],
      },
      {
        id: 7,
        units: [
          "",
          "rounded-tl shadow-itIl",
          "rounded-none patch",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "shadow-it rounded-tr",
          "",
        ],
      },
      {
        id: 8,
        units: [
          "rounded-tl shadow-itIl endzone-c",
          "rounded-none patch",
          "rounded-none",
          "rounded-none endzone-q",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "shadow-it rounded-tr",
        ],
      },
      {
        id: 9,
        units: [
          "shadow-il",
          "rounded-none endzone-k",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none endzone-l",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
        ],
      },
      {
        id: 10,
        units: [
          "shadow-il",
          "rounded-none",
          "rounded-none",
          "rounded-none endzone-e marker:bg-anthracite-500",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none endzone-d marker:bg-blue-500",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
        ],
      },
      {
        id: 11,
        units: [
          "rounded-bl shadow-il",
          "rounded-none",
          "rounded-none",
          "rounded-none marker:bg-anthracite-500",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none marker:bg-blue-500",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-br",
        ],
      },
      {
        id: 12,
        units: [
          "",
          "shadow-il",
          "rounded-none",
          "rounded-none",
          "rounded-none endzone-m marker:bg-magenta-500",
          "rounded-none endzone-r marker:bg-magenta-500",
          "rounded-none marker:bg-magenta-500",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none endzone-h",
          "",
        ],
      },
      {
        id: 13,
        units: [
          "",
          "shadow-il",
          "rounded-none endzone-p",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "",
        ],
      },
      {
        id: 14,
        units: [
          "",
          "shadow-il endzone-j marker:bg-anthracite-500",
          "rounded-none ",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "",
        ],
      },
      {
        id: 15,
        units: [
          "",
          "shadow-il marker:bg-anthracite-500",
          "rounded-none ",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "",
        ],
      },
      {
        id: 16,
        units: [
          "",
          "rounded-bl shadow-il marker:bg-anthracite-500",
          "rounded-none marker:bg-anthracite-500",
          "rounded-none ",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "rounded-none",
          "",
          "rounded-none shadow-il",
          "rounded-r shadow-it",
        ],
      },
      {
        id: 17,
        units: [
          "",
          "",
          "bg-transparent endzone-i",
          "",
          "shadow-il",
          "",
          "",
          "",
          "shadow-il endzone-b",
          "",
          "",
          "",
          "",
        ],
      },
      {
        id: 18,
        units: [
          "",
          "",
          "rounded-l shadow-itIl",
          "shadow-it",
          "rounded-br patch",
          "",
          "",
          "",
          "shadow-il rounded-bl",
          "shadow-it rounded-r",
          "",
          "",
          "",
        ],
      },
    ],
  },
};

export default slots;
